### ISSUE TITLE
low ages > 0?

### ISSUE THREAD

**Issue by timriffe** [mpascariu/pclm#1]
Hi!
Thanks for packaging this! I tried using it to graduate birth counts in 5-year age groups, ages 15-55. The following is a reproducible example:

```
libary(pclm)
B <- c(0, 1947, 10665, 16927, 17224, 13176, 7167, 1508, 33)
breaks <- seq(10,55,by=5)
bout <- pclm(dta = B, breaks)
head(bout$fitted.values)
         value  lower.bound  upper.bound
1 1.740166e-22 4.255267e-65 7.116307e+20
2 4.402209e-21 2.886459e-61 6.713918e+19
3 1.113655e-19 1.957959e-57 6.334284e+18
4 2.817283e-18 1.328134e-53 5.976117e+17
5 7.127060e-17 9.009074e-50 5.638203e+16
6 1.802978e-15 6.111083e-46 5.319399e+15
```
I can work with this because the values < 15 are so low. I added the zero for ages 10-14 to try to make it stop there, or at least put in 0s, but it goes all the way to zero in any case. Do you think you can make the function keep estimates constrained within the bounds of ```breaks```? I looked in the code and found this line:

```
m = rev(breaks)[1]
```
and that looks to be where the issue starts. Of course, this might be a feature rather than a bug, so sorry if so! For now I plan to sum values below age 12 or 15 into that age, and it won't make a big difference, so no worries. Best,
Tim

**Comment by timriffe** [comment]
Ah, I have a better solution:

```

B <- c(1947, 10665, 16927, 17224, 13176, 7167, 1508, 33)
breaks <- seq(15,55,by=5)-15
bout <- pclm(dta = B, breaks)
head(bout$fitted.values)
```
just fake that my data starts at age 0... The ages can be overwritten later. Also no need to tack on a 0 below the lower age. Thanks again for the package!

**Comment by mpascariu** [comment]
Hi Tim,
Thanks for showing interest in this package and for spotting the issue.
Please check again your first example, it should be working fine now. However around very small values the confidence intervals might be inaccurate. Together with Silvia we have to look into it.
Marius
